name: eco_game
description: "Game built with Flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  lottie: ^3.0.0
  flutter_vector_icons: ^2.0.0
  animated_text_kit: ^4.2.2
  google_sign_in: ^6.2.1
  firebase_core: ^2.25.4
  flame_audio: ^2.1.8
  flutter_fgbg: ^0.3.0
  cached_network_image: ^3.3.1
  pixelarticons: ^0.4.0
  shared_preferences: ^2.2.2
  cloud_firestore: ^4.15.4
  dartz: ^0.10.1
  uuid: ^4.3.3
  get_it: ^7.6.7
  jiffy: ^6.2.2
  percent_indicator: ^4.2.3
  blurrycontainer: ^1.0.2
  device_info_plus: ^9.1.2
  google_sign_in_web: ^0.12.3+2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
  build_runner: ^2.4.8
  freezed_annotation: ^2.4.1
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  freezed: ^2.4.6

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/jpg/app_logo.jpg"
  web:
    generate: true
    image_path: "assets/images/jpg/app_logo.jpg"
flutter:

  uses-material-design: true

  assets:
    - assets/images/game_assets/village/images/cars/
    - assets/images/game_assets/village/images/Road Signs/
    - assets/audio/
    - assets/
    - assets/images/
    - assets/images/png/
    - assets/images/jpg/
    - assets/images/game_assets/button/images/
    - assets/images/game_assets/character/spritesheets/Original/Without Outline/
    - assets/images/game_assets/character/images/portraits/Pixel-Portraits-Free/Feminine_A/
    - assets/lottie/
    - assets/images/game_assets/village/images/
  #   - images/a_dot_ham.jpeg
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
