// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWlHysBdU8CC8piBXlVhps_JL6WBcAU08',
    appId: '1:1041174152296:web:b775847fd82785e4a7e7dd',
    messagingSenderId: '1041174152296',
    projectId: 'eco-game-780c7',
    authDomain: 'eco-game-780c7.firebaseapp.com',
    storageBucket: 'eco-game-780c7.appspot.com',
    measurementId: 'G-CN5M1K6D2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHm9oYvo0zfHYtVl2uf4-xjqiMDEQ1cS8',
    appId: '1:1041174152296:android:05804c893d4a01dba7e7dd',
    messagingSenderId: '1041174152296',
    projectId: 'eco-game-780c7',
    storageBucket: 'eco-game-780c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUWyf0EVF5dL7t_bBH35HacoECAGFluTQ',
    appId: '1:1041174152296:ios:e1ae8ebccb98179aa7e7dd',
    messagingSenderId: '1041174152296',
    projectId: 'eco-game-780c7',
    storageBucket: 'eco-game-780c7.appspot.com',
    androidClientId: '1041174152296-jji6u717puen903en9j1t9bihr0eefv8.apps.googleusercontent.com',
    iosClientId: '1041174152296-886m27ahs052q64uldmatc5appecsc1f.apps.googleusercontent.com',
    iosBundleId: 'com.hedev.ecoGame',
  );
}
